apiVersion: v1
kind: Service
metadata:
  labels:
    app: s3-awssb
  name: s3-test-app-zw
  namespace: zw-project
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: s3-awssb
  type: LoadBalancer
