apiVersion: v1
kind: Pod
metadata:
  name: s3-test-app-zw
  labels:
    app: s3-awssb
  namespace: zw-project
spec:
  containers:
  - name: s3-test-app-zw
    image: docker.io/amanzh/awssb-s3:latest
    env:
      - name: S3_BUCKET_ARN
        valueFrom:
          secretKeyRef:
            name: s3-zw
            key: BUCKET_ARN
      - name: S3_BUCKET_NAME
        valueFrom:
          secretKeyRef:
            name: s3-zw
            key: BUCKET_NAME
      - name: S3_LOGGING_BUCKET_NAME
        valueFrom:
          secretKeyRef:
            name: s3-zw
            key: LOGGING_BUCKET_NAME
      - name: S3_AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: s3-zw
            key: S3_AWS_ACCESS_KEY_ID
      - name: S3_AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: s3-zw
            key: S3_AWS_SECRET_ACCESS_KEY
      - name: S3_REGION
        valueFrom:
          secretKeyRef:
            name: s3-zw
            key: S3_REGION
  restartPolicy: Never
